# 基础镜像
FROM alpine:latest

# 维护者信息
MAINTAINER toby

# 镜像操作命令


# USER toby
WORKDIR /tmp
ENV HOSTNAME linux-host

# docker build -t tfangz/alpine-libwebsockets:0.1 /home/toby/dockers/alpine-libwebsockets/
# apk add libwebsockets  for 0.2

# docker commit -a "toby" -m "libwebsockets" 4c48167241d2  tfangz/alpine-libwebsockets:0.2                                                                                                                                         
# docker tag tfangz/alpine-libwebsockets:0.2 tfangz/alpine-libwebsockets-dev:libwebsockets
