# 基础镜像
FROM alpine:latest

# 维护者信息
MAINTAINER toby

# 镜像操作命令


# USER toby
WORKDIR /tmp
ENV HOSTNAME linux-host

# docker build -t tfangz/alpine-libwebsockets-dev:0.1 /home/toby/dockers/alpine-libwebsockets-dev/
# apk add libwebsockets-dev  for 0.2

# docker commit -a "toby" -m "libwebsockets-dev" 4c48167241d2  tfangz/alpine-libwebsockets-dev:0.2
# docker tag tfangz/alpine-libwebsockets-dev:0.2 tfangz/alpine-libwebsockets-dev:libwebsockets-dev

# apk add g++
# apk add cmake
# apk add libressl-dev
# apk add libwebsockets-dev


# apk add linux-headers for 0.3

# apk add --no-cache make for 0.4
