# 基础镜像
FROM alpine:latest

# 维护者信息
MAINTAINER toby

# 镜像操作命令


# USER toby
WORKDIR /tmp
ENV HOSTNAME linux-host
# ENV HTTP_PROXY proxy
# ENV HTTPS_PROXY proxy


# 容器启动命令
# CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
